server:
  port: 9192

spring:
  cloud:
    stream:
      function:
        definition: orderPurchaseEventPublisher;transactionEventProcessor;
      bindings:
        orderPurchaseEventPublisher-out-0:
          destination: orders
        transactionEventProcessor-in-0:
          destination: transactions
          
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    maximum-pool-size: 100
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
